### ISSUE TITLE
This is showing up if i access a site from outside of the US

### ISSUE THREAD

**Issue by hishnash** [fightforthefuture/battleforthenet-widget#100]
there is not point at all in annoying users if their ISP is not inside the US. Sending a letter to U.S. Congress will not have any affect on my local ISP.

**Comment by parachutingturtle** [comment]
Agreed. I care about net neutrality, I do think it's important, and I'd sign any worldwide petition for it, but writing to the U.S. congress doesn't make any sense for me.

I find it odd that some of the most vocal proponents of a movement about the _world wide web_ keep defaulting to one country.

**Comment by Feefers** [comment]
https://en.wikipedia.org/wiki/Net_neutrality#By_country provides other by country situational reports that may effect you and you can use today as a reminder to write to your representative about how bad things are in the US and that you are very glad they wouldn't do anything like that.

**Comment by jdc20181** [comment]
Indeed, however, this campaign (while it is) isn't neccessary a world wide campaign (Right now in this moment) , it is reflecting the FCC in the US about having a session and voting on to remove Net neutrality laws.

**Comment by MrStonedOne** [comment]
the send a message box needs to be better, it assumes you are in USA

**Comment by mikemorris** [comment]
https://github.com/fightforthefuture/battleforthenet-widget/pull/121 changed the widget action 
to be even more US-centric, so we added a donate link with a specific callout for `Not in the US?` to help us continue this fight!

**Comment by chrisx84** [comment]
im a canadian but am all for net neutrality world wide so i put the html code up on both of my canadian hosted websites because this whole FCC bs will affect my websites

**Comment by kenmickles** [comment]
Moving this discussion to #145
