### ISSUE TITLE
button doesn’t look like button on mobile, battleforthenet.com

### ISSUE THREAD

**Issue by JTIII** [fightforthefuture/battleforthenet-widget#108]
button doesn’t look like button on mobile, battleforthenet.com

https://files.slack.com/files-tmb/T03A47071-F68FZ7G30-cd0d222084/image_uploaded_from_ios_1024.jpg

**Comment by mikemorris** [comment]
Wrong repo, please open a new ticket in https://github.com/fightforthefuture/battleforthenet
