### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by JTIII** [fightforthefuture/battleforthenet-widget#111]
I tried to submit the form on  Comcast wants to control what you do online. Do you want to let them?, but got a there was an error submitting the form.  In the chrome console, there seems to be a CORS error

![1499867411549blob](https://user-images.githubusercontent.com/15023208/28129201-7beb8126-6700-11e7-9d1a-74df2f1765d0.jpg)

**Comment by mikemorris** [comment]
As surfaced in https://github.com/fightforthefuture/battleforthenet-widget/issues/102#issuecomment-314826701, it appears the backend app is failing to set CORS headers for non-2xx responses. I've scaled up to handle additional load, and I'm tracking that change in the backend app.

**Comment by mikemorris** [comment]
Reopening this because it looks like our backend app wasnt sending CORS headers at all ☹️

**Comment by mikemorris** [comment]
Now sending `access-control-allow-origin:*` in responses!

/cc @as-com
