### ISSUE TITLE
load failures and cross-origin resource sharing errors

### ISSUE THREAD

**Issue by JTIII** [fightforthefuture/battleforthenet-widget#112]
Hey guys,

There are load failures and cross-origin resource sharing errors on https://www.battleforthenet.com/ that leads to the action form not working.

Screenshot from Chrome's console: http://i.imgur.com/2bL3HlT.png

Thanks so much for everything you guys are doing and if I can help with anything please let me know.

**Comment by mikemorris** [comment]
Dupe of #111, now fixed!
