### ISSUE TITLE
Question: Collaboration Continuing after today

### ISSUE THREAD

**Issue by jdc20181** [fightforthefuture/battleforthenet-widget#120]
What will we do to continue our communication after today? Is there someone who has a gitter room or something? Just curious, I want to continue to raise awareness even after today about this issue.

**Comment by mikemorris** [comment]
We're getting ready to kick off a new version of this widget to push calls to Congress! GitHub issues and pull requests will continue to be the best way to contribute to the development of this widget, but we'd also encourage you to sign up for Fight for the Future's email list at https://www.fightforthefuture.org/ ❤️

**Comment by textdog** [comment]
You could also join our volunteer slack channel!

**Comment by jdc20181** [comment]
@textdog  Please provide the link Thanks!
