### ISSUE TITLE
doesn't appear

### ISSUE THREAD

**Issue by LinuxRocks2000** [fightforthefuture/battleforthenet-widget#131]
i have a [github site](https://linuxrocks2000.github.io), when i tried to embed nothing popped up. i inspected everything and the embed was there, just not functional.

**Comment by rubbingalcoholic** [comment]
I visited your site and the embed appears to be working – it’s configured by default to use a cookie so it only shows up once per user. Perhaps try clearing your cookies and check again.

Let me know if there’s still an issue. Thanks for your support on this campaign!


From: LinuxRocks2000
Sent: Sunday, November 19, 2017 9:21 AM
To: fightforthefuture/battleforthenet-widget
Cc: Subscribed
Subject: [fightforthefuture/battleforthenet-widget] doesn't appear (#131)

i have a github site, when i tried to embed nothing popped up. i inspected everything and the embed was there, just not functional.
