### ISSUE TITLE
Server error 500/404

### ISSUE THREAD

**Issue by MulleDK19** [fightforthefuture/battleforthenet-widget#132]
Whenever I add the widget script to my site, it doesn't show up, but the entire page is uninteractable and if I check the source there's an iframe with a server error and 404.

http://ragepluginhook.net

If I append #ALWAYS_SHOW_BFTN_WIDGET, it'll show up on the second time I navigate to the page. Uninteractable, though.

**Comment by nwithan8** [comment]
Seems to work for me when I just visited on mobile.
