### ISSUE TITLE
Dokuwiki instructions?

### ISSUE THREAD

**Issue by zoof** [fightforthefuture/battleforthenet-widget#141]
Can anyone provide instructions for embedding in a dokuwiki site?

**Comment by citricsquid** [comment]
I don't have experience with Dokuwiki but the principle for using the widget is that the HTML should be included in every page, therefore, in theory, the way to achieve this with DokuWiki is to identify where your template is defined and then paste the HTML there.

Reading [the documentation here](https://www.dokuwiki.org/devel:templates) I believe that you need to do the following:

1. Navigate to the file manager for your DokuWiki installation
2. Navigate to the template directory — `lib/tpl/dokuwiki`
3. Open the `tpl_header.php` file
4. Place the widget HTML on line 9, before `<!-- ********** HEADER ********** -->`.

This is what it looks like now:

```php
<?php
/**
 * Template header, included in the main and detail files
 */
// must be run from within DokuWiki
if (!defined('DOKU_INC')) die();
?>

<!-- ********** HEADER ********** -->
<div id="dokuwiki__header"><div class="pad group">
```

And this is with the widget included:

```php
<?php
/**
 * Template header, included in the main and detail files
 */
// must be run from within DokuWiki
if (!defined('DOKU_INC')) die();
?>

<!-- ********** HEADER ********** -->
<script src="https://widget.battleforthenet.com/widget.js" async></script>
<div id="dokuwiki__header"><div class="pad group">
```

Let me know if you need any further help.

**Comment by zoof** [comment]
Many thanks!  I'm not using the default template but that was enough to get me going.
