### ISSUE TITLE
Widget is not working

### ISSUE THREAD

**Issue by Tannerghosen** [fightforthefuture/battleforthenet-widget#142]
From your website, the "place anywhere on your webpage" countdown widgets is not working on my website.
https://tannerghosen.github.io/fcc.html
I placed the widget in, only changing
`<div><script src="//fightforthefuture.github.io/countdown-widget/widget.min.js"></script></div>`
to
`<div><script src="https://fightforthefuture.github.io/countdown-widget/widget.min.js"></script></div>`
Am I missing something? Do I need a specific version of jQuery to run this? Could my website's scripts and stylesheet be effecting it?
Additionally: This is not the first widget I tested - they all aren't showing up.

**Comment by rubbingalcoholic** [comment]
Please let us know where you got that embed code – it doesn’t look right and we may need to update it.

Please give this embed code a try and let me know if that works:

<script src="https://widget.battleforthenet.com/widget.js" async></script>


From: Tanner Ghosen
Sent: Tuesday, December 12, 2017 3:40 PM
To: fightforthefuture/battleforthenet-widget
Cc: Subscribed
Subject: [fightforthefuture/battleforthenet-widget] Widget is not working(#142)

From your website, the "place anywhere on your webpage" countdown widgets is not working on my website.
https://tannerghosen.github.io/fcc.html
I placed the widget in, only changing
<div><script src="//fightforthefuture.github.io/countdown-widget/widget.min.js"></script></div
to
'
<script src="https://fightforthefuture.github.io/countdown-widget/widget.min.js"></script></div'
Am I missing something? Do I need a specific version of jQuery to run this? Could my website's scripts and stylesheet be effecting it?
Additionally: This is not the first widget I tested - they all aren't showing up.

**Comment by Tannerghosen** [comment]
Thank you. Closing issue.
