### ISSUE TITLE
Waiting for the phone call form battleforthenet to call a representative.

### ISSUE THREAD

**Issue by w1ll01** [fightforthefuture/battleforthenet-widget#146]
I gave my phone number and am still waiting for the call.  I may need call them manually.

**Comment by rubbingalcoholic** [comment]
Hello – I’m trying to rule out the possibility that our phone system is under heavy load and dropping calls. If you’re comfortable doing so, please send an email to jeff@fightforthefuture.org with your phone number and I can look it up in our logs to see what happened.

From: w1ll01
Sent: Wednesday, December 13, 2017 4:37 PM
To: fightforthefuture/battleforthenet-widget
Cc: Subscribed
Subject: [fightforthefuture/battleforthenet-widget] Waiting for the phone callform battleforthenet to call a representative. (#146)

I gave my phone number and am still waiting for the call. I may need call them manually.
