### ISSUE TITLE
Update for 2017 -- July 11th

### ISSUE THREAD

**Issue by mekarpeles** [fightforthefuture/battleforthenet-widget#15]
To oppose FCC docket 17-108

**Comment by nickstew** [comment]
> "Internet-Wide Day of Action to Save Net Neutrality” on July 12
> via [Netflix joins Amazon and Reddit in Day of Action to save net neutrality](https://arstechnica.com/tech-policy/2017/06/netflix-re-joins-fight-to-save-net-neutrality-rules/)

Is there another project like this one or would you like me to submit a PR on this project, @rubbingalcoholic?

**Comment by mekarpeles** [comment]
I think this should be closed -- https://www.battleforthenet.com/july12/
Re-open if there's not consensus

**Comment by mikemorris** [comment]
@mekarpeles Reopening as we are planning to also update this widget (which people can add to their own sites to participate) for the July 12th day of action, and this is a good first step!
