### ISSUE TITLE
Disable popup

### ISSUE THREAD

**Issue by misterquiggles** [fightforthefuture/battleforthenet-widget#150]
Hello, 

My last ticket was closed without anybody responding. 

I was wondering how I can disable these political popups. 

Thanks.

-Q

**Comment by RookyGhost** [comment]
hello there Quiggles, I'm not affiliated by any means to the developer of the script, but I would suggest you to just ignore them.
whether you consider the motion to be political or business-motivated, it's not up to the developer but to the webmaster to choose between including them or not.
you'd be better off just clicking away, and have a good day!

**Comment by misterquiggles** [comment]
Alright, thought there might be a way to disable it. Thanks anyways!

**Comment by kenmickles** [comment]
Closing this since it's basically the same as #145. @misterquiggles if you really don't want to see this popup (or any other content you don't like), I'd recommend checking out an ad blocking extension for your browser. It's pretty easy to configure them to block specific domains.
