### ISSUE TITLE
Time stuck at 0:00 indefinatly

### ISSUE THREAD

**Issue by Electromaster232** [fightforthefuture/battleforthenet-widget#152]
After the widget was updated to reflect the resolution of disapproval, the time indefinitely shows as 0:00 for all fields. I'm not sure if this is because there is no time to set (unfortunately I haven't had alot of time lately to read up on whether or not there is a date set for the Congress vote) or if its some other issue.

![screen shot 2017-12-18 at 2 48 46 pm](https://user-images.githubusercontent.com/25728719/34124978-d6718382-e402-11e7-90dc-65ce365d0910.png)

**Comment by M-C-Cookies** [comment]
There is no vote time anywhere near set. As of now, I do not believe that Congress has publicly released any consideration of this.

**Comment by rubbingalcoholic** [comment]
We'll update the countdown when there's a new vote incoming. For the time being we recommend sites use one of the other themes for the widget.
