### ISSUE TITLE
Mixed content error

### ISSUE THREAD

**Issue by trfalb** [fightforthefuture/battleforthenet-widget#19]
I installed the script in WordPress using wp_enqueue_script in functions.php. It worked on my test site, but not on my live site because of mixed content. Error appeared in Chrome, Firefox, and Safari. 
Error message:
Mixed Content: The page at 'https://example.com/#ALWAYS_SHOW_BFTN_WIDGET' was loaded over HTTPS, but requested an insecure resource 'http://widget.battleforthenet.com/iframe/iframe.html'. This request has been blocked; the content must be served over HTTPS.

**Comment by CodeMouse92** [comment]
Getting this as well. All my sites are served over HTTPS, so this is SUPER important to be fixed.

**Comment by Ipstenu** [comment]
https://github.com/fightforthefuture/battleforthenet-widget/blob/master/widget.js#L3 has the correct code (https) and so does https://widget.battleforthenet.com/widget.js so this is really quite odd.

**Comment by Josh6680** [comment]
It appears the widget.js loads the iframe over https:
`https://fightforthefuture.github.io/battleforthenet-widget/iframe/iframe.html`
however it actually gets redirected to a non-https url:
`http://widget.battleforthenet.com/iframe/iframe.html`

Looks like you can add this option in JS as a workaround, but the ideal solution would be fixing that redirect.
```javascript
var _bftn_options = {
	iframe_base_path: 'https://widget.battleforthenet.com/iframe'
};
```

**Comment by CodeMouse92** [comment]
If it helps, here's a live page that has the widget AND the error in question: https://mousepawmedia.com/company#ALWAYS_SHOW_BFTN_WIDGET

**Comment by Ipstenu** [comment]
@Josh6680 nailed it. If I edit @CodeMouse92's page to this:

```
<iframe id="_bftn_iframe" src="https://widget.battleforthenet.com/iframe/iframe.html" frameborder="0" style="display: block;"></iframe>
```

It works. Pull request sent.
