### ISSUE TITLE
Instructions for WordPress?

### ISSUE THREAD

**Issue by davecotter** [fightforthefuture/battleforthenet-widget#20]
got'ny?

**Comment by davecotter** [comment]
[this seems out of date](https://wordpress.org/plugins/stopsopa-again/), and i don't want a sidebar widget, i just want the overlay widget

**Comment by Ipstenu** [comment]
Unofficial plugin - https://wordpress.org/plugins/fftf-alerts/

Currently throwing mixed content errors on https sites, related to #19
