### ISSUE TITLE
widget assumes that web site visitors are Americans

### ISSUE THREAD

**Issue by mbelmonte** [fightforthefuture/battleforthenet-widget#21]
The widget asks all visitors to "contact Congress and the FCC".  Many countries have congresses, and most people in the world aren't going to know what the three letters 'FCC' stand for, or what a "ZIP" code is.  (And what about American citizens residing outside their country, who are entitled to representation but have no ZIP codes?)  The trouble with Americans is that they assume that theirs is the only country in the world of any consequence.  To help dispel this attitude, I suggest the following revised text:

"Cable companies want to get rid of net neutrality.  Without it, sites like ours could be censored, slowed down, or forced to charge extra fees.  We can stop them and keep the Internet open, fast, and awesome if people contact the US Congress and Federal Communications Commission, but we only have a few days left.  If you're a citizen or resident of the United States, please act now!"

**Comment by niccokunzmann** [comment]
I do not know if this is only important for citizens of the United States. I would sign it even if I am an outsider just so they know people from all over the world are watching.
