### ISSUE TITLE
IE11/Edge Style and Layout Issues

### ISSUE THREAD

**Issue by decoy31** [fightforthefuture/battleforthenet-widget#32]
Here's what it looks like on a Windows 8.1 VM in Internet Explorer 11:
![win8 1-ie11](https://user-images.githubusercontent.com/1266335/27923330-e0ad3802-6232-11e7-9f98-e732ade4b83a.png)

It looks similar in Edge on Windows 8.1.

**Comment by decoy31** [comment]
I'll take a crack at fixing this issue. (This is a ship blocker for the site I am working on.)

**Comment by mikemorris** [comment]
Would greatly appreciate style tweaks to fix this!
