### ISSUE TITLE
404 error when we clicked the "Privacy policy" link in the widget.

### ISSUE THREAD

**Issue by vsraghavan89** [fightforthefuture/battleforthenet-widget#40]
Link to reproduce the issue : https://www.screencast.com/t/rLRgJXb08zQa

**Comment by mikemorris** [comment]
This was fixed in https://github.com/fightforthefuture/battleforthenet-widget/commit/0155920949fb39bb00a03f7cba0f327e25e71f83, and should be working now if you're pulling in the remote widget code. If you've embedded the widget code manually, you should apply this patch.
