### ISSUE TITLE
Widget doesn't show up for the first time when s user tries to access the site

### ISSUE THREAD

**Issue by vsraghavan89** [fightforthefuture/battleforthenet-widget#41]
We have noticed that the widget did not show up for the first time in any of the test branch servers. We were able to get the widget only by appending #ALWAYS_SHOW_BFTN_WIDGET to the url.

**Comment by rubbingalcoholic** [comment]
Past widgets were set up to only fire on the day of action. If you clear cookies and set your computer's clock to July 12, does the widget display as expected?

**Comment by mikemorris** [comment]
Per email, this is has been resolved - [setting a custom `date` in `_bftn_options`](https://github.com/fightforthefuture/battleforthenet-widget/blob/master/README.md#modal-customization-options) is another option for testing.
