### ISSUE TITLE
Minimized/optimized builds for production?

### ISSUE THREAD

**Issue by EdenSG** [fightforthefuture/battleforthenet-widget#43]
I was able to reduce filesize 22% overall on these files:

- 30% on `widget.js` with `uglifyjs`
- 23% on `script.js` with `uglifyjs`
- 24% on `style.css` with `csso`

Additionally, I was able to save 58% on the SVGs with `svgo`.

I'd be happy to write a pre-commit script that would automatically run these optimizations, but it'd also require a bit of a restructure of the repo. We could keep all the files in the same directory, and just add `min` to the minified files (`widget.min.js` and so on), or we could use a separate directory (`min` or `prod` or something) where all the minified files are kept. I'm leaning towards the latter method, since it'd mean the minify script would just have to copy everything over and minify all the files, whereas if we kept files in place the script would need to modify references in files (change `src="script.js"` to `src="script.min.js"` in `iframe.html`, and so on).

**Comment by mikemorris** [comment]
This would be wonderful if you want to take it on!

The ideal would be keeping generated code of of version control to avoid messy diffs - bundling production assets into a `dist` dir would be a good start, would be excellent to get this into a [CI script pushing the contents of that dir to a `gh-pages` branch for publishing](https://github.com/fightforthefuture/rockagainstthetpp/blob/production/scripts/deploy-ghpages.sh).

Were you thinking of using Webpack, Gulp, Grunt, or something else?
