### ISSUE TITLE
Widget might appear on the wrong date, depending on user's time zone

### ISSUE THREAD

**Issue by rlineweaver** [fightforthefuture/battleforthenet-widget#45]
![image](https://user-images.githubusercontent.com/58700/27976251-b3f8ba32-6333-11e7-9674-351b99bdc21d.png)

My computer is in EDT.  If I set my computer clock to July 12, the widget does not appear.  If I set it to July 11, it does.  I think this is because (new Date('2017-07-12')).getDate() is 11 in my time zone, not 12.

**Comment by dsanders11** [comment]
@rlineweaver, good catch. Seems like that's a flaw in the current current implementation. Looks like this would be better:

````javascript
new Date(2017, 6 /* Zero-based month */, 12)
````

That seems to behave like one would expect.
