### ISSUE TITLE
non US addresses

### ISSUE THREAD

**Issue by nonUSA** [fightforthefuture/battleforthenet-widget#46]
Hi I have a large audience outside of the US, is it valid to send letters from non-US citizens? I notice there is only a ZIP code box in the form. Thanks!

**Comment by mikemorris** [comment]
Form submissions from non-US citizens are okay! If a non-US postcode is entered the FCC comment will still be submitted, but no matching Congressional representatives will be found, so a letter won't be sent to Congress.
