### ISSUE TITLE
In <head> or <body>

### ISSUE THREAD

**Issue by sojourner1** [fightforthefuture/battleforthenet-widget#51]
Do I put the <script src="https://widget.battleforthenet.com/widget.js" async></script> code in the <head> section of my website or in the <body> section? Does it matter where in the section it's placed?

Thanks. 

Bruce

**Comment by Retroity** [comment]
I'd put in <head>, as this is done in [the demo](https://github.com/fightforthefuture/battleforthenet-widget/blob/master/demos/modal.html).

**Comment by mikemorris** [comment]
Either should be fine @sojourner1!
