### ISSUE TITLE
Widget closing by mistake

### ISSUE THREAD

**Issue by JTIII** [fightforthefuture/battleforthenet-widget#59]
It seems like if the user clicks outside of the foreground widget window (for example anywhere else in the main webpage window), the widget closes (or maybe is just backgrounded?). This could confuse/discourage users-- fix it so the widget window remains in the foreground until the form is submitted?

**Comment by mikemorris** [comment]
This is very much intentional behavior and is typical for modals, should it be removed?

**Comment by decoy31** [comment]
I agree with @mikemorris. Being able to click outside of a modal to close is an established web user experience and would likely cause user frustration if not implemented. That being said, would giving the developer a configuration option to disable background-click-to-close be a better compromise?

**Comment by mikemorris** [comment]
This sounds like a user issue and not a dev issue, so I don't think a dev option would help.
