### ISSUE TITLE
Action button not responding in Safari

### ISSUE THREAD

**Issue by JTIII** [fightforthefuture/battleforthenet-widget#61]
The actions link button did not respond on Safari 10.1.1 on MacOS 10.12.5

**Comment by mikemorris** [comment]
The `Protest` after-action button was previously labeled `Attend an Action` before recently merging https://github.com/fightforthefuture/battleforthenet-widget/pull/53 and it did not link anywhere at that point. Closing this as resolved, please reopen if I'm misinterpreting the issue.
