### ISSUE TITLE
Form layout issue in IE11

### ISSUE THREAD

**Issue by rlineweaver** [fightforthefuture/battleforthenet-widget#69]
In Internet Explorer 11, the form doesn't layout correctly:

![image](https://user-images.githubusercontent.com/58700/28032186-9e378746-6577-11e7-8add-07fafaefaaac.png)

Potential fix is around line 150 of style.css, under `.modal form .flex`, add a new CSS rule:

`min-width: 43%;`

Then it looks like:

![image](https://user-images.githubusercontent.com/58700/28032304-012ea28a-6578-11e7-8899-285508fb730c.png)

**Comment by mikemorris** [comment]
Thanks for catching this @rlineweaver, I probably broke it when switching from `ZIP` to `Postcode`
