### ISSUE TITLE
Default date set to June 12, 2017

### ISSUE THREAD

**Issue by elexlee** [fightforthefuture/battleforthenet-widget#70]
`  if (typeof _bftn_options.date == "undefined") _bftn_options.date = new Date(2017, 6 /* Zero-based month */, 12);
`

Saw that it was 6-12-2017 in widget.js. Should it be 7-12-2017?
Same thing is going on in the modal customization options.

`/*
     * Specify a date on which to display the widget. Defaults to July 12th, 2017 if 
     * omitted. ISO-8601 dates are UTC time, three-argument dates (with a zero-based
     * month) are local time.
     */
    date: new Date(2017, 6, 12), // @type {Date}`

**Comment by dudeman** [comment]
Comments say it's a zero based month. So 0 would be January and 6 would be July.  Seems correct if that's the case.

**Comment by elexlee** [comment]
Ahh ok. Wasn't quite sure what that meant but thanks for clarifying!

**Comment by dudeman** [comment]
No problem! 🍻
