### ISSUE TITLE
On desktop Safari, Address and Postcode form fields should be full width

### ISSUE THREAD

**Issue by bfalling** [fightforthefuture/battleforthenet-widget#72]
On wide viewports with Mac Safari 10.1.1, the "This site has been blocked by your ISP" popup's Address and Postcode form fields don't fill the form width, and I believe they should.

![pasted_image_7_10_17__1_08_pm](https://user-images.githubusercontent.com/1231433/28037759-65440e24-6571-11e7-8dfc-d78506a7300c.png)

**Comment by mikemorris** [comment]
Should've just fixed this in https://github.com/fightforthefuture/battleforthenet-widget/commit/c5b3119be2d02667b6acb17ebf175704c9922ca9

**Comment by jdc20181** [comment]
@mikemorris You should close this please

Thanks!
