### ISSUE TITLE
Quick comment field style tweak to make the FCC form less daunting

### ISSUE THREAD

**Issue by bfalling** [fightforthefuture/battleforthenet-widget#73]
Currently, the FCC form is a bit scary with all its form fields. The final field containing the pre-filled long-form content is a little confusing because it's sized like a normal form field but has more than 1 line of content.

By increasing its height and distinguishing its background, the long-form content field can be made to look more like a typical textarea, which is a friendlier call-out because: 1) users recognize it as a free-form field (which is often optional), and 2) it's already filled out with useful content.

An example style tweak for that textarea, with screenshot:
```
background-color: rgba(102, 121, 252, 0.14);
height: 88px;
```

![screen_shot_2017-07-10_at_11_55_49ampdt](https://user-images.githubusercontent.com/1231433/28038129-b7437e34-6572-11e7-92f6-53ad6735823b.png)

**Comment by mikemorris** [comment]
Agree with your concerns and this has been an ongoing challenge for us, but after talking with @katro16 I don't think this suggestion solves the issue.

The increased height adds a lot of vertical space and we've already have been struggling with that on smaller screens, and the `background-color` on `textarea` makes it look even more busy and could be mistaken for a cue that the field is not editable.

**Comment by bfalling** [comment]
No problem. That was just an example of the *kinds* of tweaking that I came up with in the moment. Glad you all have been thinking about the issue.
