### ISSUE TITLE
Loading icon not animating

### ISSUE THREAD

**Issue by wisticott** [fightforthefuture/battleforthenet-widget#77]
In the popup/modal, the loading icon (leftmost icon) is not animating. **This is a problem because it just looks like an asterisk otherwise.** To the ordinary users who this tool is intended to reach, since they are not graphic designers working on a net neutrality campaign, they have never seen this icon "not animating", which means it's broken as far as communicating the necessary message. Sorry if this crucial requirement doesn't make for "tidy" graphic design, but it's important to stress the current failure of the modal, which is the first thing anyone sees, to explain "the web without Net Neutrality" (what is that exactly? A web full of cryptic icons that only have obvious ominous significance to people who are already net neutrality activists?) To be effective, the modal must have **some** kind of immediately, instantaneous meaning, and for many users the only instant pathway to mapping this political issue onto their existing brain circuitry is with the "loading animation" - this was surely a part of the success of the iconic previous campaign.

**Comment by mikemorris** [comment]
You can you the `theme: 'slow'` variation where the icon spins if you want.

**Comment by holmesworcester** [comment]
I'd like to leave this open if we have time. People can still change.
