### ISSUE TITLE
"Issues" link closes modal, but doesn't open Issues page

### ISSUE THREAD

**Issue by mbrailer** [fightforthefuture/battleforthenet-widget#78]
On Chrome and Firefox (OSX), clicking the "Issues?" link at the bottom of the modal window closes the window but doesn't open the GitHub page in the link. I can right click and select "Open in New Tab" and then the page loads.

On desktop Safari, clicking the link does nothing. Again, right click and "Open in New Tab" does work.

**Comment by mikemorris** [comment]
Good catch, just fixed, thanks!
