### ISSUE TITLE
On desktop Safari, all fields appear on one row

### ISSUE THREAD

**Issue by mbrailer** [fightforthefuture/battleforthenet-widget#79]
This is what I see on Safari (OSX). The modal is centered in the screen, and the fields continue past the right edge of the window. If I scroll the window to the right, the remaining fields and the submit button appear, all on the same horizontal line.

![2017-07-10 08 35 21 pm](https://user-images.githubusercontent.com/30061369/28046110-52a6b198-65af-11e7-88bd-4c34a679c139.png)

**Comment by jglass** [comment]
I can report I am having the same issue on iOS 10.2.1, I may try to update later to see if that fixes it. Also, the modal is not centered properly for me

**Comment by chrisvogt** [comment]
This is what I'm seeing using [BrowserStack](https://www.browserstack.com), which may also be reproducing part of #63.

###### iPhone 6S & Safari
![igdrepiihz](https://user-images.githubusercontent.com/1934719/28052928-97aec718-65c2-11e7-93e4-119f8ce7b25e.gif)

###### iPhone 6S  & Chrome
![chrome](https://user-images.githubusercontent.com/1934719/28052991-00587836-65c3-11e7-9e55-8698a475f8e6.gif)

###### Nexus 6P & Chrome
![screen shot 2017-07-10 at 10 58 49 pm](https://user-images.githubusercontent.com/1934719/28053071-67682648-65c3-11e7-96ae-298263d0615a.png)

###### Nexus 6P & Firefox
![screen shot 2017-07-10 at 10 59 45 pm](https://user-images.githubusercontent.com/1934719/28053096-8b3e6546-65c3-11e7-9766-608e77b05797.png)

**Comment by decoy31** [comment]
Has anyone started work on this issue? I will go ahead and start looking into fixing this issue now, while I wait to hear back. This is a ship blocker for the site I work on.

I cannot repro this issue in desktop Safari (v10.1.1), but I can reproduce it in the iOS 10.2 simulator. Here's an example showing the iPad Retina:
![ipad retina](https://user-images.githubusercontent.com/1266335/28078198-eb358290-6618-11e7-8697-b016e350c9cd.png)
**NOTE:** On page load, the dialog appeared partially on the right hand side of the screen. To capture this screenshot, I had to scroll to the right to center the dialog on the screen. The form elements continue to the right as others have described.

**Comment by mikemorris** [comment]
Would love your help working on a PR to fix this @decoy31! I've been completely swamped the past few days and haven't had time to start working on this. FWIW, I'd suspect it's a flexbox bug in Safari (but I'm not able to reproduce on the most recent version), maybe something around not respecting an implicit `max-width`?

**Comment by holmesworcester** [comment]
I can't reproduce in latest Safari desktop either. @decoy31 any progress?

**Comment by decoy31** [comment]
No progress yet. I had some meetings today pull me away from this. Will start in on it now.

**Comment by mikemorris** [comment]
Just tested and I'm not able to reproduce in iOS 10.3 Simulator either. iPhone 6 and iPad Air 2 both display fine.

**Comment by mikemorris** [comment]
@decoy31 This looks like https://stackoverflow.com/questions/36636243/flex-items-not-stacking-properly-in-safari could be the culprit here.

**Comment by decoy31** [comment]
Nice! Good find. I will definitely take a look into that.

**Comment by decoy31** [comment]
I'm having difficulties with my Windows VM. Any chance someone can verify the PR changes work in IE11/Edge?

**Comment by mikemorris** [comment]
@decoy31 I can check on an IE11 VM later tonight. BrowserStack has free Edge testing.
