### ISSUE TITLE
Continues to show

### ISSUE THREAD

**Issue by aikar** [fightforthefuture/battleforthenet-widget#93]
Even after seen, the modal keeps popping up. Had to take it off site due to this :/

Even happens on the demo page:
https://www.battleforthenet.com/july12/

Chrome for Linux

**Comment by mikemorris** [comment]
Did you have `always_show_widget: true` in the config options? If so you can just remove that line to have the expected behavior. Preventing future popups of the widget also does require cookies.

**Comment by Zenexer** [comment]
This is happening with the Cloudflare app, too, and there's no option to disable it.  Our non-American users in particular are complaining quite a bit, since they can't actually fill out the form.

**Comment by aikar** [comment]
I did not set any configs. just the script tag...

**Comment by Zenexer** [comment]
Here's one complaint saying that it keeps popping up even after we switched away from the Cloudflare app: https://www.namepros.com/posts/6253707/  I wasn't able to reproduce the issue, but it sounds like it's on iOS.

**Comment by Zenexer** [comment]
@aikar I explicitly set the value to `false` and that seems to have worked.

More updates on the complaint: https://www.namepros.com/posts/6253756/ (also see response in following post)

**Comment by Zenexer** [comment]
Found the bug.  It's not setting `path=/` for the cookie.

**Comment by aikar** [comment]
@Zenexer  I noticed that too

**Comment by tibetsprague** [comment]
good catch!

**Comment by mikemorris** [comment]
That would do it - thanks for catching this @Zenexer!
